name: selection
dependencies:
  - python=3.12
  - pip
  - boto3
  - conda-forge::gcc_linux-64  # Correct GCC package for Linux. Necessary for triton.  
  - pip:
      - mlflow
      - psutil
      - radt
      - torch
      - torchvision
      - torchaudio
      - torchtext
      - torchao
      - torchtune
      - bitsandbytes
      - lm_eval==0.4.*
      - traker[fast]==0.1.3 # for LESS
