name: selection
dependencies:
  - python=3.12
  - pip
  - boto3
  - conda-forge::gxx_linux-64=12
  - conda-forge::gcc_linux-64=12  # Correct GCC package for Linux. Necessary for triton.
  - nvidia/label/cuda-12.4.0::cuda-toolkit
conda install pytorch==2.5.1 torchvision==0.20.1 torchaudio==2.5.1 pytorch-cuda=12.4 -c pytorch -c nvidia  
  # - pip:
  #     - mlflow
  #     - psutil
  #     - radt
  #     - torch # Dont do this
  #     - torchvision # Dont do this
  #     - torchaudio # Dont do this
  #     - torchtext
  #     - torchao
  #     - torchtune
  #     - bitsandbytes
  #     - lm_eval==0.4.*
  #     - traker[fast]==0.1.3 # for LESS
