training_gradient_path: None
train_file_names: None
epochs: "1, 2, 3, 4"



# argparser = argparse.ArgumentParser(
#     description='Script for selecting the data for training')
# argparser.add_argument('--gradient_path', type=str, default="{} ckpt{}",
#                        help='The path to the gradient file')
# argparser.add_argument('--train_file_names', type=str, nargs='+',
#                        help='The name of the training file')
# argparser.add_argument('--ckpts', type=int, nargs='+',
#                        help="Checkpoint numbers.")
# argparser.add_argument('--checkpoint_weights', type=float, nargs='+',
#                        help="checkpoint weights")
# argparser.add_argument('--target_task_names', type=str,
#                        nargs='+', help="The name of the target tasks")
# argparser.add_argument('--validation_gradient_path', type=str,
#                        default="{} ckpt{}", help='The path to the validation gradient file')
# argparser.add_argument('--output_path', type=str, default="selected_data",
#                        help='The path to the output')